### ISSUE TITLE
CSS issues with details on Firefox

### ISSUE THREAD

**Issue by stlozhaw** [sustainability-zhaw/sustainability-dashboard#113]
Firefox
![dashboard-firefox](https://user-images.githubusercontent.com/89318491/230418686-6c14b0c8-0def-4e15-ad24-77a82789de24.PNG)

Chrome
![dashboard-chrome](https://user-images.githubusercontent.com/89318491/230418761-062aeac1-c4b5-45b8-98d7-216276828329.PNG)

**Comment by phish108** [comment]
Thank you. 

The CSS uses the [:has() selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has). The problem is that FF is the [last browser to fully support this selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility).

The Issue will be fixed as soon as the selector is officially released.

see also: 

- [The upstream bug](https://bugzilla.mozilla.org/show_bug.cgi?id=418039)
- [The release plan reference](https://connect.mozilla.org/t5/discussions/when-is-has-css-selector-going-to-be-fully-implemented-in/m-p/27010/highlight/true#M10711)

**Comment by phish108** [comment]
according to caniuse has() will be fixed with firefox version 121 in Decemeber 2023

**Comment by stlozhaw** [comment]
Works now with the latest version `121.0`.
